# Generated by Django 2.2.7 on 2020-07-16 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('telefono', models.CharField(max_length=8)),
                ('direccion', models.CharField(max_length=150)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(default='', max_length=50)),
                ('precioventa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('preciocompra', models.DecimalField(decimal_places=2, max_digits=5)),
                ('existencia', models.IntegerField()),
                ('promocion', models.BooleanField(default=False)),
                ('fkcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Categoria')),
                ('fkproveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Proveedor')),
            ],
        ),
    ]
