# Generated by Django 2.2.4 on 2020-11-25 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('comentario', models.CharField(max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cobrar', models.BooleanField(default=False)),
                ('archivada', models.BooleanField(default=False)),
            ],
        ),
    ]
