# Generated by Django 2.2.4 on 2020-07-16 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaIncidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=150)),
                ('fkCategoriaIncidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.CategoriaIncidencia')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='fkIncidencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.Incidencia'),
        ),
    ]
