# Generated by Django 2.2.4 on 2020-07-17 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20200716_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fkIncidencia',
        ),
        migrations.AddField(
            model_name='incidencia',
            name='fkProducto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.Producto'),
        ),
    ]
