# Generated by Django 2.2.7 on 2021-01-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20210105_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='nombreRepresentante',
            field=models.CharField(max_length=35),
        ),
    ]
