# Generated by Django 2.2.7 on 2021-01-06 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20210106_1412'),
        ('inventario', '0006_producto_minimo'),
    ]

    operations = [
    ]
