# Generated by Django 2.2.7 on 2020-07-16 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0002_producto_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exito', models.BooleanField(default=False)),
                ('cancelado', models.BooleanField(default=False)),
                ('pendiente', models.BooleanField(default=True)),
                ('subtotal', models.FloatField(default=0, null=True)),
                ('display', models.BooleanField(default=False)),
                ('fechaPedido', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='detalle_Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('subtotal', models.FloatField(default=0, null=True)),
                ('comentario', models.CharField(blank=True, max_length=60)),
                ('fkPedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.Pedido')),
                ('fkProducto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.Producto')),
            ],
        ),
    ]
