# Generated by Django 2.2.7 on 2020-07-17 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=60)),
                ('detalle', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exito', models.BooleanField(default=False)),
                ('cancelado', models.BooleanField(default=False)),
                ('pendiente', models.BooleanField(default=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('display', models.BooleanField(default=False)),
                ('fechaPedido', models.DateTimeField(auto_now=True)),
                ('fkProveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('fk_Tipo_Pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.Tipo_Pago')),
                ('fk_pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.Pedido')),
            ],
        ),
        migrations.CreateModel(
            name='detalle_Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('comentario', models.CharField(blank=True, max_length=60)),
                ('fkPedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.Pedido')),
                ('fkProducto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.Producto')),
            ],
        ),
    ]
