# Generated by Django 2.2.5 on 2020-07-14 22:58

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('direccion', models.TextField(blank=True, max_length=60)),
                ('mobile', phone_field.models.PhoneField(blank=True, help_text='Agregar numero telefonico', max_length=31, unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('precioCompra', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('precioVenta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('existencia', models.PositiveIntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=60)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.Proveedor')),
            ],
        ),
    ]
