# Generated by Django 2.2.7 on 2020-07-15 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
