# Generated by Django 2.2.7 on 2021-01-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pedido',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
