# Generated by Django 2.2.7 on 2020-07-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_pedido_fkproveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_pedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
