# Generated by Django 2.2.7 on 2021-01-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_pedido_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='pedido',
            new_name='comentario',
        ),
    ]
