# Generated by Django 2.2.7 on 2020-09-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=8, unique=True)),
                ('dui', models.CharField(max_length=9, unique=True)),
                ('nit', models.CharField(max_length=14, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
    ]
