# Generated by Django 2.2.7 on 2020-09-20 23:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='usuario',
        ),
        migrations.AddField(
            model_name='empleado',
            name='clave',
            field=models.CharField(default=1, max_length=4, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='El # ingresado es invalido, Debe tener 8 caracteres', regex='^.{8}$')]),
            preserve_default=False,
        ),
    ]
