# Generated by Django 2.2.7 on 2020-09-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.CharField(max_length=50),
        ),
    ]
