# Generated by Django 2.2.7 on 2020-09-21 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('ventas', '0002_auto_20200920_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipoPago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.Tipo_Pago'),
        ),
    ]
