# Generated by Django 2.2.7 on 2020-10-13 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_auto_20200920_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='meta_asignadafk',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='tipo_meta',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Diaria'), (2, 'Quincenal'), (3, 'Mensual')], default=1),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='dui',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='El DUI ingresado es invalido, Debe tener 9 caracteres', regex='^.{10}$')]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='El # ingresado es invalido, Debe tener 9 caracteres', regex='^.{8}$')]),
        ),
    ]
