# Generated by Django 2.2.4 on 2021-01-05 01:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_auto_20201013_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='dui',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='El DUI ingresado es invalido, Debe tener 9 caracteres', regex='^.{9}$')]),
        ),
        migrations.AlterUniqueTogether(
            name='asignacion',
            unique_together=set(),
        ),
    ]
