# Generated by Django 2.2.7 on 2021-01-06 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_auto_20210104_1924'),
        ('ventas', '0006_auto_20210104_1353'),
    ]

    operations = [
    ]
