# Generated by Django 2.2.7 on 2021-01-06 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_merge_20210106_1411'),
        ('ventas', '0007_merge_20210106_0514'),
    ]

    operations = [
    ]
