# Generated by Django 2.2.7 on 2021-01-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_merge_20210106_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iva', models.IntegerField(default=0.13)),
                ('pagoIva', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
