# Generated by Django 2.2.7 on 2021-01-06 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_renta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='renta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.Renta'),
        ),
    ]
