# Generated by Django 2.2.7 on 2021-01-07 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_pedido_renta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='renta',
            field=models.ForeignKey(default=0.13, on_delete=django.db.models.deletion.CASCADE, to='ventas.Renta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='renta',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.13, max_digits=6),
        ),
        migrations.AlterField(
            model_name='renta',
            name='pagoIva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
