# Generated by Django 2.2.7 on 2021-01-07 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_auto_20210107_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='renta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.Renta'),
        ),
    ]
