# Generated by Django 2.2.7 on 2021-01-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_auto_20210107_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='renta',
            name='totalPagar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
